branches:
  only:
  - master
addons:
  homebrew:
    taps: discoteq/discoteq
    packages:
      - bash
      #- wget
      - make
      - lhasa
      #- gmp
      #- mpfr
      #- libmpc
      - flex
      - gettext
      - texinfo
      #- gcc
      #- autoconf
      - flock
matrix:
  include:
    - os: osx
      osx_image: xcode10.2
      sudo: required
      language: c
      before_install:
        #- ls -l /usr/local/bin
        - sudo mkdir /opt/amiga && sudo chown $(whoami) /opt/amiga
script:
 - echo ${TRAVIS_OS_NAME}
 #- if [ "${TRAVIS_OS_NAME}" == "osx" ]; then export SHELL=/usr/local/bin/bash; fi
 - if [ "${TRAVIS_OS_NAME}" == "osx" ]; then CC=gcc-8 CXX=g++-8 gmake all -j3; else make all -j3; fi
 - tar czf amiga-gcc-${TRAVIS_OS_NAME}.tgz /opt/amiga
 - ls -l
after_failure:
  - cat log/*.log