branches:
  only:
  - master
matrix:
  include:
    - os: linux
      dist: trusty
      sudo: required
      language: c
      before_install:
        - sudo apt-get install -y make git gcc g++ lhasa libgmp-dev libmpfr-dev libmpc-dev flex gettext texinfo
        - sudo mkdir /opt/amiga && sudo chown $(whoami) /opt/amiga
    - os: osx
      sudo: required
      language: c
      before_install:
        - brew install libmpc util-linux gcc make
        - brew tap discoteq/discoteq; brew install flock
        - sudo mkdir /opt/amiga && sudo chown $(whoami) /opt/amiga
script:
 - echo ${TRAVIS_OS_NAME}
 - if [ "${TRAVIS_OS_NAME}" == "osx" ]; then CC=gcc-9 CXX=g++-9 gmake all -j3; else make all -j3; fi
 - tar czf amiga-gcc-${TRAVIS_OS_NAME}.tgz /opt/amiga
 - ls -l
