branches:
  only:
  - master
addons:
  homebrew:
    taps: discoteq/discoteq
    packages:
      - bash
      - make
      - lhasa
      - flex
      - gettext
      - texinfo
      - flock
      # already installed
      #- gcc
      #- autoconf
      #- wget
      #- gmp
      #- mpfr
      #- libmpc
matrix:
  include:
    - os: osx
      osx_image: xcode10.2
      sudo: required
      language: c
      before_install:
        - sudo mkdir /opt/amiga && sudo chown $(whoami) /opt/amiga
script:
 - echo ${TRAVIS_OS_NAME}
 - if [ "${TRAVIS_OS_NAME}" == "osx" ]; then CC=gcc-8 CXX=g++-8 travis_wait 30 gmake all -j3; else make all -j3; fi
 - tar czf amiga-gcc-${TRAVIS_OS_NAME}.tgz /opt/amiga
 - ls -l
after_failure:
  - cat log/*.log