language: c
before_install: sudo apt-get install make git gcc g++ lhasa libgmp-dev libmpfr-dev libmpc-dev flex gettext texinfo
install: make update -j
script: 
- make info PREFIX=$PWD/prefix
- make all -j PREFIX=$PWD/prefix
- make sdk=mui -j PREFIX=$PWD/prefix
- make sdk=mmu -j PREFIX=$PWD/prefix
- echo "done"
