branches:
  only:
  - master
addons:
  homebrew:
    taps: discoteq/discoteq
    packages:
      - bash
      - make
      - lhasa
      - flex
      - gettext
      - texinfo
      - flock
      # needed but already installed : gcc autoconf wget gmp mpfr libmpc
matrix:
  include:
    - os: osx
      osx_image: xcode10.2
      sudo: required
      language: c
      before_install:
        - sudo mkdir /opt/amiga && sudo chown $(whoami) /opt/amiga
script:
  - if [ "${TRAVIS_OS_NAME}" == "osx" ];
    then 
      export CC=gcc-8;
      export CXX=g++-8;
      travis_wait 60 gmake all -j3;
    else
      make all -j3;
    fi
after_failure:
  - cat log/*.log